- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest


- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist

- name: Install NodeJs
  ansible.builtin.apt:
    name: nodejs
    state: present

- name: Run the equivalent of "apt-get clean" as a separate step
  ansible.builtin.apt:
    clean: yes