- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest


- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist

- name: Add NodeSource repository for Node.js 20.x
  ansible.builtin.shell: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -

- name: Install Node.js
  ansible.builtin.package:
      name: nodejs
      state: present




- name: Run the equivalent of "apt-get clean" as a separate step
  ansible.builtin.apt:
    clean: yes